services:
    blogfinity:
        image: wlczak/blogfinity:latest
        labels:
            - com.centurylinklabs.watchtower.enable=true
        volumes:
            # - ./:/app # For local development
            - ./db/:/app/db/
            - ./logger/logs/:/app/logger/logs/
            - ./:/app/conf/
        working_dir: /app
        restart: always
        environment:
            - OLLAMA_SERVER_IPS=${OLLAMA_SERVER_IPS}
        extra_hosts:
            # For local ollama backup
            - "host.docker.internal:host-gateway"
        ports:
            - "1111:8080"
        command: ./blogfinity
        networks:
            - blogfinity-net
    qdrant:
        image: qdrant/qdrant:v1.17-unprivileged
        ports:
            - "6333:6333" # REST API + dashboard
        volumes:
            - qdrant_data:/qdrant/storage
        restart: unless-stopped

volumes:
    qdrant_data:

networks:
    blogfinity-net:
        name: blogfinity-net
